### ISSUE TITLE
[EKS] [request]: BUG: Windows Nodes fail to join cluster from the US-WEST-2 LAX Local Zones

### ISSUE THREAD

**Issue by jjooky** [aws/containers-roadmap#1147]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
EKS Windows Nodes in the **US-WEST-2-LAX** Local Zones fail to join the EKS Cluster in the parent region **us-west-2** because the `Start-EKSBootstrap.ps1` script is setting a bad `--region` value for in the **kubeconfig** that the **kubelet** uses for communication to the EKS Cluster.

**Which service(s) is this request for?**
 EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
The Windows `Start-EKSBootstrap.ps1` script is getting a local availability zone which is then used in the **kubeconfig** config region for the **kubelet** to use. The issue here is that the instance running in the local zone `us-west-2-lax-1a` attempts to start the **kubelet** using that local zone as the region to reach the EKS Cluster Control Plane. But, as we know, there is no EKS Control Plane support in the **us-west-2 LAX** local zones yet. So the **kubelet** fails to register.

Snippet from the `Start-EKSBootstrap.ps1` that sets the wrong region for the Cluster Control Plane in reference to a Local Zone Instance:
```
  [string]$ZONE = Get-EC2MetaData 'latest/meta-data/placement/availability-zone'
  [string]$AWS_REGION = $ZONE.Substring(0, $ZONE.length - 1)
```

**Are you currently working around this issue?**
There are no work arounds to support changing the way the script is setting the **kubeconfig** with the proper **region**

**Additional context**
Tested a one-off change with an instance by modifying the `Start-EKSBootstrap.ps1` in place to use the `us-west-2` region via the Environment Variable: **AWS_DEFAULT_REGION**.

Modified script snippet:
```
  #[string]$ZONE = Get-EC2MetaData 'latest/meta-data/placement/availability-zone'
  [string]$AWS_REGION = $AWS_DEFAULT_REGION
```
Ultimately the **kubeconfig** that the **kubelet** is using should reference the EKS Control Plane with a valid region where the Control is actively available.

**Attachments**
--

**Comment by lalwanin2020** [comment]
Hi all
We have made the required changes and the changes will be made available in the next month's EKS AMIs. 

Thanks 
Naveen Lalwani

**Comment by mikestef9** [comment]
This has been resolved with the latest EKS Windows AMI releases

**Comment by jjooky** [comment]
/reopen

This is not resolved. AWS EKS Team forced our hand to upgrade to server 2004 or use Server 2019 Full while the rest of the industry is still supporting Windows Server 1909.

This has left our Windows clusters in an incomplete state as other supporting applications/services are not able to run on the 2004 node groups (FluentD and NewRelic Daemonsets don't support 2004)

This is not resolved for the 1909 AMI as that was never updated and has since been deprecated.
