### ISSUE TITLE
Targets not deregistered after task is stopped, serious routing issue with dynamic port mapping

### ISSUE THREAD

**Issue by Vilsepi** [aws/containers-roadmap#347]
The agent sometimes fails to remove a target from a target group after the ECS task has stopped.

We seem to be witnessing aws/amazon-ecs-agent#500 again with agent versions 1.17.3 and 1.18.0.

We have an ECS cluster of 50 services on 10 instances. Each service has one or more tasks, and each task definition has only one container. Each container has an application port as well as couple metrics exporter service ports. We use dynamic host port mapping.

Service A started logging elevated error rates when it was calling service B, and reading the logs we noticed that it was somehow getting a reply instead from a metrics agent from Service C. Digging deeper, we found that several target groups for the services had lingering unhealthy targets. One of the healthy targets in service B's target group was the Service C's metrics agent. The agent in question is the [Prometheus node_exporter](https://github.com/prometheus/node_exporter), which unfortunately responds HTTP 200 OK no matter which path is requested from it, and thus we believe it managed to survive in the wrong target group.

We cleaned the lingering targets manually, and configured an alarm to go off if there are any unhealthy targets. Right now, we have saved some unhealthy targets in a testing environment, and continue to dig further into this. I will also contact AWS support from the Web Console.

**Comment by Mavus** [comment]
Just adding to this issue to confirm I'm still seeing this issue.
<img width="1408" alt="Screenshot+2019-07-31+at+16 26 34" src="https://user-images.githubusercontent.com/4614043/63508522-0bb37f80-c4d2-11e9-883f-6f781b75260e.png">

**Comment by vlobovikov** [comment]
HI, we have the same problem: agent version: 1.30

![Bildschirmfoto 2019-08-27 um 11 09 43](https://user-images.githubusercontent.com/29395665/63758019-6c203380-c8bb-11e9-88b0-f4d9218e52f2.png)

**Comment by matthewduren** [comment]
This also affects containers running in fargate. I have seen a handful of times across different services of ours, all running in fargate.

**Comment by woody-klaviyo** [comment]
Confirming that this is still an issue with containers in Fargate

**Comment by iniinikoski** [comment]
> This also affects containers running in fargate. I have seen a handful of times across different services of ours, all running in fargate.

Same here, Fargate. Very disturbing behaviour.

**Comment by woody-klaviyo** [comment]
For the record, AWS Support recommended that we map each service to a different subnet mask. This alleviates the vast majority of bad routing that occurs with this issue. It's not an ideal solution, but it is a relatively easy one to implement for anyone who is feeling pain from this.

**Comment by matthewduren** [comment]
We have a cluster with over 1200 services. I don't think support is going to be happy with our 1200 subnets limit increase.

Further, the bad routing is only part of the problem. The elb waiters fail to go healthy, causing automated deploys to fail.

**Comment by L3tum** [comment]
@woody-klaviyo We got the same recommendation. However, that would mean approximately 10000 subnets all manually created, assigned in Cloud formation and maintained. Yeah, no. Maybe if you only got 1-10 services that would be somewhat feasible, but I think most people impacted by this issue here are large business companies. Which is also the reason that it's astonishing that this issue is *still* open.

**Comment by woody-klaviyo** [comment]
Yeah I totally agree, just spreading word for something that *does* work, but is annoying to implement. The fact that this bug is so long-running is very frustrating. On our call, they assured us that it would be solved within a month or two, but that time-frame is already out the window.

**Comment by L3tum** [comment]
@woody-klaviyo I don't want to move too offtopic, so I'll just tag you and say this: The person responsible at my company assured me to give me an update a week later...that was 4 months ago.

**Comment by dkallakuri** [comment]
Sorry for the delay in response. We pushed functionality in 2020 to reduce the likeliness of this issue from occurring. This year we are working on adding functionality to stop this issue from occurring.

**Comment by zbintliff** [comment]
Hey @coultn and @pavneeta . I saw this was moved to "working on it". Are you able to publicly say any expected deliverable date?

**Comment by RobertWilc** [comment]
Still seeing the issue. 
![Unhealthy](https://user-images.githubusercontent.com/86537559/192320101-a9902be8-0d87-4c5d-abab-b8d38c60ccaa.png)

**Comment by OverStruck** [comment]
Issue still present in Fargate 1.4.0 when using same health check URL (i.e /status) for different services sharing same subnets in a given cluster
